name: clima
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  http: ^1.1.2
  flutter_spinkit: ^5.2.0
  intl: ^0.18.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  outline_gradient_button: ^2.0.0+1
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/images/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/OverpassBold.ttf
          weight: 700
        - asset: assets/fonts/OverpassRegular.ttf
          weight: 400
        - asset: assets/fonts/OverpassBlack.ttf
          weight: 900
        - asset: assets/fonts/OverpassLight.ttf
          weight: 300
        - asset: assets/fonts/OverpassSemiBold.ttf
          weight: 600
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayLight.ttf
          weight: 300
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
